spring:
  main:
    sources: org.foobarter.isss.store

  datasource:
    url: jdbc:postgresql://storedb.foobarter.org/isss

management:
  port: 8081

server:
  port: -1

camel:
  springboot:
    # The Camel context name
    name: ISSSStore
    main-run-controller: true

    spring:
      # Spring JDBC configuration


logging:
  config: "classpath:logback.xml"
