spring:
  main:
    sources: org.foobarter.isss.store

  datasource:
    url: jdbc:postgresql://storedb.foobarter.org/isss

management:
  port: 8081

server:
  port: -1

service:
  store:
    catalog:
      url: "http://backend.foobarter.org:8080"
    order:
      #url: "http://backend.foobarter.org:8080"
      url: "http://order.foobarter.org:8080"

camel:
  springboot:
    # The Camel context name
    name: ISSSStore
    main-run-controller: true

    spring:
      # Spring JDBC configuration

rest:
  host: "0.0.0.0"
  port: 8080


logging:
  config: "classpath:logback.xml"
